version: 0.2

phases:
  install:
    commands:
      - yum -y install sshpass
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo "Starting docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      - echo Build started on `date`
      - docker build -t kbwebapp_tag . -f ./Dockerfile
      - docker tag kbwebapp_tag 108607216059.dkr.ecr.eu-central-1.amazonaws.com/kbweb:latest
      - docker push 108607216059.dkr.ecr.eu-central-1.amazonaws.com/kbweb:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Connecting via SSH...
      - sshpass -p CodebuildTest ssh ubuntu@ec2-18-185-65-126.eu-central-1.compute.amazonaws.com <<- 'ENDSSH'
        - sudo systemctl start kbwebapp
        - ENDSSH
      - echo SSH connection is completed
